<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5.3 Tablas cruzadas | Análisis de encuestas con R</title>
  <meta name="description" content="Este es el repositorio del libro Análisis de encuestas de hogares con R." />
  <meta name="generator" content="bookdown 0.44 and GitBook 2.6.7" />

  <meta property="og:title" content="5.3 Tablas cruzadas | Análisis de encuestas con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es el repositorio del libro Análisis de encuestas de hogares con R." />
  <meta name="github-repo" content="psirusteam/2021ASDA" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5.3 Tablas cruzadas | Análisis de encuestas con R" />
  
  <meta name="twitter:description" content="Este es el repositorio del libro Análisis de encuestas de hogares con R." />
  

<meta name="author" content="Andrés Gutiérrez, Giovany Babativa-Márquez, Stalyn Guerrero, Cristian Téllez" />


<meta name="date" content="2026-04-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="estimación-de-proporciones.html"/>
<link rel="next" href="viz-categoricas.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de encuestas de hogares con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Prefacio</a></li>
<li class="chapter" data-level="1" data-path="cap-intro.html"><a href="cap-intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="05-Categóricas.html"><a href="#motivaci%C3%B3n"><i class="fa fa-check"></i><b>1.1</b> Motivación</a></li>
<li class="chapter" data-level="1.2" data-path="05-Categóricas.html"><a href="#contexto-metodol%C3%B3gico-y-estado-del-arte"><i class="fa fa-check"></i><b>1.2</b> Contexto metodológico y estado del arte</a></li>
<li class="chapter" data-level="1.3" data-path="05-Categóricas.html"><a href="#usar-r-para-el-an%C3%A1lisis-de-encuestas"><i class="fa fa-check"></i><b>1.3</b> Usar R para el análisis de encuestas</a></li>
<li class="chapter" data-level="1.4" data-path="05-Categóricas.html"><a href="#organizaci%C3%B3n"><i class="fa fa-check"></i><b>1.4</b> Organización</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="05-Categóricas.html"><a href="#parte-1-fundamentos-del-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>1.4.1</b> Parte 1: Fundamentos del diseño muestral</a></li>
<li class="chapter" data-level="1.4.2" data-path="organización.html"><a href="organización.html"><i class="fa fa-check"></i><b>1.4.2</b> Parte 2: Elementos computacionales</a></li>
<li class="chapter" data-level="1.4.3" data-path="05-Categóricas.html"><a href="#parte-3-estimaci%C3%B3n-de-par%C3%A1metros-descriptivos"><i class="fa fa-check"></i><b>1.4.3</b> Parte 3: Estimación de parámetros descriptivos</a></li>
<li class="chapter" data-level="1.4.4" data-path="05-Categóricas.html"><a href="#parte-4-modelamiento-estad%C3%ADstico"><i class="fa fa-check"></i><b>1.4.4</b> Parte 4: Modelamiento estadístico</a></li>
<li class="chapter" data-level="1.4.5" data-path="05-Categóricas.html"><a href="#parte-5-imputaci%C3%B3n"><i class="fa fa-check"></i><b>1.4.5</b> Parte 5: Imputación</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="05-Categóricas.html"><a href="#justificaci%C3%B3n-de-este-libro"><i class="fa fa-check"></i><b>1.5</b> Justificación de este libro</a></li>
<li class="chapter" data-level="1.6" data-path="perfil-del-lector.html"><a href="perfil-del-lector.html"><i class="fa fa-check"></i><b>1.6</b> Perfil del lector</a></li>
<li class="chapter" data-level="1.7" data-path="estructura.html"><a href="estructura.html"><i class="fa fa-check"></i><b>1.7</b> Estructura del libro</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-2-conceptos-b%C3%A1sicos-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>1.7.1</b> Capítulo 2: Conceptos básicos en encuestas de hogares</a></li>
<li class="chapter" data-level="1.7.2" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-3-del-manejo-de-datos-al-an%C3%A1lisis-de-encuestas-complejas-en-r"><i class="fa fa-check"></i><b>1.7.2</b> Capítulo 3: Del manejo de datos al análisis de encuestas complejas en R</a></li>
<li class="chapter" data-level="1.7.3" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-4-an%C3%A1lisis-de-variables-continuas"><i class="fa fa-check"></i><b>1.7.3</b> Capítulo 4: Análisis de variables continuas</a></li>
<li class="chapter" data-level="1.7.4" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-5-an%C3%A1lisis-de-variables-categ%C3%B3ricas"><i class="fa fa-check"></i><b>1.7.4</b> Capítulo 5: Análisis de variables categóricas</a></li>
<li class="chapter" data-level="1.7.5" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-6-modelos-de-regresi%C3%B3n"><i class="fa fa-check"></i><b>1.7.5</b> Capítulo 6: Modelos de regresión</a></li>
<li class="chapter" data-level="1.7.6" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-7-modelos-lineales-generalizados"><i class="fa fa-check"></i><b>1.7.6</b> Capítulo 7: Modelos lineales generalizados</a></li>
<li class="chapter" data-level="1.7.7" data-path="05-Categóricas.html"><a href="#cap%C3%ADtulo-9-procedimientos-de-imputaci%C3%B3n"><i class="fa fa-check"></i><b>1.7.7</b> Capítulo 9: Procedimientos de imputación</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="05-Categóricas.html"><a href="#conceptos-b%C3%A1sicos-en-encuestas-de-hogares"><i class="fa fa-check"></i><b>2</b> Conceptos básicos en encuestas de hogares</a>
<ul>
<li class="chapter" data-level="2.1" data-path="05-Categóricas.html"><a href="#universo-de-estudio-y-poblaci%C3%B3n-objetivo"><i class="fa fa-check"></i><b>2.1</b> Universo de estudio y población objetivo</a></li>
<li class="chapter" data-level="2.2" data-path="05-Categóricas.html"><a href="#unidades-de-an%C3%A1lisis"><i class="fa fa-check"></i><b>2.2</b> Unidades de análisis</a></li>
<li class="chapter" data-level="2.3" data-path="unidades-de-muestreo.html"><a href="unidades-de-muestreo.html"><i class="fa fa-check"></i><b>2.3</b> Unidades de muestreo</a></li>
<li class="chapter" data-level="2.4" data-path="marcos-de-muestreo.html"><a href="marcos-de-muestreo.html"><i class="fa fa-check"></i><b>2.4</b> Marcos de muestreo</a></li>
<li class="chapter" data-level="2.5" data-path="sec-motivacion.html"><a href="sec-motivacion.html"><i class="fa fa-check"></i><b>2.5</b> Motivación</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="05-Categóricas.html"><a href="#la-importancia-de-considerar-el-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>2.5.1</b> La importancia de considerar el diseño muestral</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="05-Categóricas.html"><a href="#par%C3%A1metros-y-estimadores"><i class="fa fa-check"></i><b>2.6</b> Parámetros y estimadores</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html"><i class="fa fa-check"></i><b>2.6.1</b> Ajustes adicionales de los pesos</a></li>
<li class="chapter" data-level="2.6.2" data-path="parámetros-y-estimadores.html"><a href="parámetros-y-estimadores.html#importancia-de-los-ajustes"><i class="fa fa-check"></i><b>2.6.2</b> Importancia de los ajustes</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales"><i class="fa fa-check"></i><b>2.7</b> Estimación de totales</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="estimación-de-totales.html"><a href="estimación-de-totales.html"><i class="fa fa-check"></i><b>2.7.1</b> Ejemplo ilustrativo</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="05-Categóricas.html"><a href="#efecto-del-dise%C3%B1o-deff"><i class="fa fa-check"></i><b>2.8</b> Efecto del diseño (DEFF)</a></li>
<li class="chapter" data-level="2.9" data-path="muestreo-estratificado-aleatorio-simple-con-dos-etapas.html"><a href="muestreo-estratificado-aleatorio-simple-con-dos-etapas.html"><i class="fa fa-check"></i><b>2.9</b> Muestreo estratificado aleatorio simple con dos etapas</a></li>
<li class="chapter" data-level="2.10" data-path="05-Categóricas.html"><a href="#pr%C3%A1ctica-en-r"><i class="fa fa-check"></i><b>2.10</b> Práctica en <code>R</code></a></li>
<li class="chapter" data-level="2.11" data-path="calibrando-con-r.html"><a href="calibrando-con-r.html"><i class="fa fa-check"></i><b>2.11</b> Calibrando con <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="05-Categóricas.html"><a href="#del-manejo-de-datos-al-an%C3%A1lisis-de-encuestas-complejas-en-r"><i class="fa fa-check"></i><b>3</b> Del manejo de datos al análisis de encuestas complejas en R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="05-Categóricas.html"><a href="#fundamentos-b%C3%A1sicos-de-r-y-rstudio"><i class="fa fa-check"></i><b>3.1</b> Fundamentos básicos de R y Rstudio</a></li>
<li class="chapter" data-level="3.2" data-path="05-Categóricas.html"><a href="#paquetes-para-el-an%C3%A1lisis-de-encuestas"><i class="fa fa-check"></i><b>3.2</b> Paquetes para el análisis de encuestas</a></li>
<li class="chapter" data-level="3.3" data-path="05-Categóricas.html"><a href="#paquetes-complementarios-para-la-manipulaci%C3%B3n-y-visualizaci%C3%B3n-de-datos"><i class="fa fa-check"></i><b>3.3</b> Paquetes complementarios para la manipulación y visualización de datos</a></li>
<li class="chapter" data-level="3.4" data-path="05-Categóricas.html"><a href="#creaci%C3%B3n-de-proyectos-en-r"><i class="fa fa-check"></i><b>3.4</b> Creación de proyectos en <code>R</code></a></li>
<li class="chapter" data-level="3.5" data-path="05-Categóricas.html"><a href="#lectura-de-bases-de-datos-y-manipulaci%C3%B3n"><i class="fa fa-check"></i><b>3.5</b> Lectura de bases de datos y manipulación</a></li>
<li class="chapter" data-level="3.6" data-path="el-operador-pipe.html"><a href="el-operador-pipe.html"><i class="fa fa-check"></i><b>3.6</b> El operador <code>pipe</code></a></li>
<li class="chapter" data-level="3.7" data-path="05-Categóricas.html"><a href="#transformaci%C3%B3n-y-resumen-de-datos"><i class="fa fa-check"></i><b>3.7</b> Transformación y resumen de datos</a></li>
<li class="chapter" data-level="3.8" data-path="05-Categóricas.html"><a href="#diferencias-entre-el-an%C3%A1lisis-tradicional-y-el-an%C3%A1lisis-de-encuestas-complejas"><i class="fa fa-check"></i><b>3.8</b> Diferencias entre el análisis tradicional y el análisis de encuestas complejas</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="cap4.html"><a href="cap4.html"><i class="fa fa-check"></i><b>4</b> Análisis de las variables continuas</a>
<ul>
<li class="chapter" data-level="4.1" data-path="05-Categóricas.html"><a href="#definici%C3%B3n-del-objeto-de-dise%C3%B1o"><i class="fa fa-check"></i><b>4.1</b> Definición del objeto de diseño</a></li>
<li class="chapter" data-level="4.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales-y-medias"><i class="fa fa-check"></i><b>4.2</b> Estimación de totales y medias</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-puntual"><i class="fa fa-check"></i><b>4.2.1</b> Estimación puntual</a></li>
<li class="chapter" data-level="4.2.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-totales-1"><i class="fa fa-check"></i><b>4.2.2</b> Estimación de totales</a></li>
<li class="chapter" data-level="4.2.3" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-la-media-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.2.3</b> Estimación de la media e intervalo de confianza</a></li>
<li class="chapter" data-level="4.2.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-medidas-de-localizaci%C3%B3n-y-dispersi%C3%B3n"><i class="fa fa-check"></i><b>4.2.4</b> Estimación de medidas de localización y dispersión</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-razones"><i class="fa fa-check"></i><b>4.3</b> Estimación de razones</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#implementaci%C3%B3n-computacional-en-r"><i class="fa fa-check"></i>Implementación computacional en <code>R</code></a></li>
<li class="chapter" data-level="" data-path=""><a href="#interpretaci%C3%B3n-aplicada"><i class="fa fa-check"></i>Interpretación aplicada</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-del-coeficiente-de-gini"><i class="fa fa-check"></i><b>4.4</b> Estimación del coeficiente de Gini</a></li>
<li class="chapter" data-level="4.5" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>4.5</b> Análisis de correlación</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="05-Categóricas.html"><a href="#ajuste-al-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>4.5.1</b> Ajuste al diseño muestral</a></li>
<li class="chapter" data-level="4.5.2" data-path="05-Categóricas.html"><a href="#expresi%C3%B3n-formal"><i class="fa fa-check"></i><b>4.5.2</b> Expresión formal</a></li>
<li class="chapter" data-level="4.5.3" data-path="05-Categóricas.html"><a href="#implementaci%C3%B3n-en-r"><i class="fa fa-check"></i><b>4.5.3</b> Implementación en R</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="05-Categóricas.html"><a href="#pruebas-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>4.6</b> Pruebas de hipótesis</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html"><i class="fa fa-check"></i><b>4.6.1</b> Planteamiento general</a></li>
<li class="chapter" data-level="4.6.2" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#prueba-para-la-diferencia-de-medias"><i class="fa fa-check"></i><b>4.6.2</b> Prueba para la diferencia de medias</a></li>
<li class="chapter" data-level="4.6.3" data-path="05-Categóricas.html"><a href="#estad%C3%ADstico-de-prueba-e-intervalo-de-confianza"><i class="fa fa-check"></i><b>4.6.3</b> Estadístico de prueba e intervalo de confianza</a></li>
<li class="chapter" data-level="4.6.4" data-path="pruebas-de-hipótesis.html"><a href="pruebas-de-hipótesis.html#ejemplo-aplicado-en-r"><i class="fa fa-check"></i><b>4.6.4</b> Ejemplo aplicado en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-contrastes"><i class="fa fa-check"></i><b>4.7</b> Estimación de contrastes</a></li>
<li class="chapter" data-level="4.8" data-path="viz-continuas.html"><a href="viz-continuas.html"><i class="fa fa-check"></i><b>4.8</b> Visualización de variables continuas</a>
<ul>
<li class="chapter" data-level="4.8.1" data-path="viz-continuas.html"><a href="viz-continuas.html#histogramas"><i class="fa fa-check"></i><b>4.8.1</b> Histogramas</a></li>
<li class="chapter" data-level="4.8.2" data-path="viz-continuas.html"><a href="viz-continuas.html#densidades-y-boxplots"><i class="fa fa-check"></i><b>4.8.2</b> Densidades y Boxplots</a></li>
<li class="chapter" data-level="4.8.3" data-path="05-Categóricas.html"><a href="#diagramas-de-dispersi%C3%B3n"><i class="fa fa-check"></i><b>4.8.3</b> Diagramas de dispersión</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="05-Categóricas.html"><a href="#an%C3%A1lisis-de-variables-categ%C3%B3ricas"><i class="fa fa-check"></i><b>5</b> Análisis de variables categóricas</a>
<ul>
<li class="chapter" data-level="5.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-del-tama%C3%B1o-poblacional"><i class="fa fa-check"></i><b>5.1</b> Estimación del tamaño poblacional</a>
<ul>
<li class="chapter" data-level="" data-path=""><a href="#estimaci%C3%B3n-de-totales-en-r"><i class="fa fa-check"></i>Estimación de totales en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones"><i class="fa fa-check"></i><b>5.2</b> Estimación de proporciones</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones-en-r"><i class="fa fa-check"></i><b>5.2.1</b> Estimación de proporciones en <code>R</code></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html"><i class="fa fa-check"></i><b>5.3</b> Tablas cruzadas</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="05-Categóricas.html"><a href="#definici%C3%B3n-y-notaci%C3%B3n"><i class="fa fa-check"></i><b>5.3.1</b> Definición y notación</a></li>
<li class="chapter" data-level="5.3.2" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#tablas-de-doble-entrada"><i class="fa fa-check"></i><b>5.3.2</b> Tablas de doble entrada</a></li>
<li class="chapter" data-level="5.3.3" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#proporciones-para-variables-binarias"><i class="fa fa-check"></i><b>5.3.3</b> Proporciones para variables binarias</a></li>
<li class="chapter" data-level="5.3.4" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#proporciones-para-variables-multinomiales"><i class="fa fa-check"></i><b>5.3.4</b> Proporciones para variables multinomiales</a></li>
<li class="chapter" data-level="5.3.5" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#tablas-cruzadas-o-de-contingencia"><i class="fa fa-check"></i><b>5.3.5</b> Tablas cruzadas o de contingencia</a></li>
<li class="chapter" data-level="5.3.6" data-path="tablas-cruzadas.html"><a href="tablas-cruzadas.html#prueba-de-independencia-chi2"><i class="fa fa-check"></i><b>5.3.6</b> Prueba de independencia <span class="math inline">\(\chi^{2}\)</span></a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="viz-categoricas.html"><a href="viz-categoricas.html"><i class="fa fa-check"></i><b>5.4</b> Visualización de variables categóricas</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="05-Categóricas.html"><a href="#gr%C3%A1ficos-de-barras"><i class="fa fa-check"></i><b>5.4.1</b> Gráficos de barras</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="viz-mapas.html"><a href="viz-mapas.html"><i class="fa fa-check"></i><b>5.5</b> Visualización de variables categóricas en mapas</a>
<ul>
<li class="chapter" data-level="5.5.1" data-path="viz-mapas.html"><a href="viz-mapas.html#carga-del-shapefile-y-mapa-base"><i class="fa fa-check"></i><b>5.5.1</b> Carga del shapefile y mapa base</a></li>
<li class="chapter" data-level="5.5.2" data-path="05-Categóricas.html"><a href="#mapa-coropl%C3%A9tico-de-pobreza-masculina-por-regi%C3%B3n"><i class="fa fa-check"></i><b>5.5.2</b> Mapa coroplético de pobreza masculina por región</a></li>
<li class="chapter" data-level="5.5.3" data-path="05-Categóricas.html"><a href="#mapa-del-coeficiente-de-variaci%C3%B3n-del-ingreso-medio"><i class="fa fa-check"></i><b>5.5.3</b> Mapa del coeficiente de variación del ingreso medio</a></li>
<li class="chapter" data-level="5.5.4" data-path="viz-mapas.html"><a href="viz-mapas.html#mapa-bivariante-con-ggplot2"><i class="fa fa-check"></i><b>5.5.4</b> Mapa bivariante con <code>ggplot2</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="cap6.html"><a href="cap6.html"><i class="fa fa-check"></i><b>6</b> Modelos de regresión</a>
<ul>
<li class="chapter" data-level="6.1" data-path="05-Categóricas.html"><a href="#antecedentes-hist%C3%B3ricos-y-desarrollos-metodol%C3%B3gicos"><i class="fa fa-check"></i><b>6.1</b> Antecedentes históricos y desarrollos metodológicos</a></li>
<li class="chapter" data-level="6.2" data-path="05-Categóricas.html"><a href="#relevancia-pr%C3%A1ctica"><i class="fa fa-check"></i><b>6.2</b> Relevancia práctica</a></li>
<li class="chapter" data-level="6.3" data-path="uso-de-ponderaciones.html"><a href="uso-de-ponderaciones.html"><i class="fa fa-check"></i><b>6.3</b> Uso de ponderaciones</a></li>
<li class="chapter" data-level="6.4" data-path="enfoques-inferenciales.html"><a href="enfoques-inferenciales.html"><i class="fa fa-check"></i><b>6.4</b> Enfoques inferenciales</a></li>
<li class="chapter" data-level="6.5" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-los-par%C3%A1metros"><i class="fa fa-check"></i><b>6.5</b> Estimación de los parámetros</a></li>
<li class="chapter" data-level="6.6" data-path="05-Categóricas.html"><a href="#diagn%C3%B3stico-del-modelo"><i class="fa fa-check"></i><b>6.6</b> Diagnóstico del modelo</a>
<ul>
<li class="chapter" data-level="6.6.1" data-path="05-Categóricas.html"><a href="#coeficiente-de-determinaci%C3%B3n"><i class="fa fa-check"></i><b>6.6.1</b> Coeficiente de determinación</a></li>
<li class="chapter" data-level="6.6.2" data-path="05-Categóricas.html"><a href="#diagn%C3%B3stico-de-los-residuales"><i class="fa fa-check"></i><b>6.6.2</b> Diagnóstico de los residuales</a></li>
<li class="chapter" data-level="6.6.3" data-path="diagnóstico-del-modelo.html"><a href="diagnóstico-del-modelo.html"><i class="fa fa-check"></i><b>6.6.3</b> Observaciones influyentes</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="05-Categóricas.html"><a href="#inferencia-sobre-los-par%C3%A1metros-del-modelo"><i class="fa fa-check"></i><b>6.7</b> Inferencia sobre los parámetros del modelo</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-puntual-e-intervalo-de-predicci%C3%B3n"><i class="fa fa-check"></i><b>6.7.1</b> Estimación puntual e intervalo de predicción</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="cap-glm.html"><a href="cap-glm.html"><i class="fa fa-check"></i><b>7</b> Modelos lineales generalizados</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sec-mpv.html"><a href="sec-mpv.html"><i class="fa fa-check"></i><b>7.1</b> Inferencia en poblaciones finitas</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="sec-mpv.html"><a href="sec-mpv.html#sec-mv"><i class="fa fa-check"></i><b>7.1.1</b> Método de la máxima verosimilitud</a></li>
<li class="chapter" data-level="7.1.2" data-path="sec-mpv.html"><a href="sec-mpv.html#sec-mpv-formal"><i class="fa fa-check"></i><b>7.1.2</b> Método de máxima pseudo-verosimilitud</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="05-Categóricas.html"><a href="#configuraci%C3%B3n-del-dise%C3%B1o-muestral"><i class="fa fa-check"></i><b>7.2</b> Configuración del diseño muestral</a></li>
<li class="chapter" data-level="7.3" data-path="sec-independencia.html"><a href="sec-independencia.html"><i class="fa fa-check"></i><b>7.3</b> Tablas de contingencia y pruebas de independencia</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="sec-independencia.html"><a href="sec-independencia.html#sec-rao-scott"><i class="fa fa-check"></i><b>7.3.1</b> Prueba de Rao-Scott</a></li>
<li class="chapter" data-level="7.3.2" data-path="sec-independencia.html"><a href="sec-independencia.html#sec-wald"><i class="fa fa-check"></i><b>7.3.2</b> Estadístico de Wald</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="sec-loglineal.html"><a href="sec-loglineal.html"><i class="fa fa-check"></i><b>7.4</b> Modelo log-lineal para tablas de contingencia</a></li>
<li class="chapter" data-level="7.5" data-path="sec-logistica.html"><a href="sec-logistica.html"><i class="fa fa-check"></i><b>7.5</b> Modelo de regresión logística</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="sec-logistica.html"><a href="sec-logistica.html#modelo-sin-interacciones"><i class="fa fa-check"></i><b>7.5.1</b> Modelo sin interacciones</a></li>
<li class="chapter" data-level="7.5.2" data-path="sec-logistica.html"><a href="sec-logistica.html#modelo-con-interacciones"><i class="fa fa-check"></i><b>7.5.2</b> Modelo con interacciones</a></li>
<li class="chapter" data-level="7.5.3" data-path="sec-logistica.html"><a href="sec-logistica.html#modelo-con-pesos-q-weighted"><i class="fa fa-check"></i><b>7.5.3</b> Modelo con pesos q-weighted</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="sec-gamma.html"><a href="sec-gamma.html"><i class="fa fa-check"></i><b>7.6</b> Modelo de regresión Gamma</a></li>
<li class="chapter" data-level="7.7" data-path="sec-multinomial.html"><a href="sec-multinomial.html"><i class="fa fa-check"></i><b>7.7</b> Modelo de regresión multinomial</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="sec-multinomial.html"><a href="sec-multinomial.html#ajuste-usando-svyvgam"><i class="fa fa-check"></i><b>7.7.1</b> Ajuste usando <code>svyVGAM</code></a></li>
<li class="chapter" data-level="7.7.2" data-path="sec-multinomial.html"><a href="sec-multinomial.html#ajuste-usando-svymultinom"><i class="fa fa-check"></i><b>7.7.2</b> Ajuste usando <code>svymultinom</code></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="cap-multinivel.html"><a href="cap-multinivel.html"><i class="fa fa-check"></i><b>8</b> Modelos multinivel</a>
<ul>
<li class="chapter" data-level="8.1" data-path="sec-motivacionMult.html"><a href="sec-motivacionMult.html"><i class="fa fa-check"></i><b>8.1</b> Motivación: de la regresión clásica al modelo multinivel</a></li>
<li class="chapter" data-level="8.2" data-path="sec-multinivel-muestras-complejas.html"><a href="sec-multinivel-muestras-complejas.html"><i class="fa fa-check"></i><b>8.2</b> Modelos multinivel en muestras complejas</a></li>
<li class="chapter" data-level="8.3" data-path="sec-mpv-multinivel.html"><a href="sec-mpv-multinivel.html"><i class="fa fa-check"></i><b>8.3</b> Estimación de pseudo-máxima verosimilitud</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="sec-mpv-multinivel.html"><a href="sec-mpv-multinivel.html#pesos-de-muestreo-para-modelos-multinivel"><i class="fa fa-check"></i><b>8.3.1</b> Pesos de muestreo para modelos multinivel</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="sec-modelo-nulo.html"><a href="sec-modelo-nulo.html"><i class="fa fa-check"></i><b>8.4</b> Modelo nulo</a></li>
<li class="chapter" data-level="8.5" data-path="sec-intercepto-aleatorio.html"><a href="sec-intercepto-aleatorio.html"><i class="fa fa-check"></i><b>8.5</b> Modelo con intercepto aleatorio</a></li>
<li class="chapter" data-level="8.6" data-path="sec-intercepto-pendiente-aleatorios.html"><a href="sec-intercepto-pendiente-aleatorios.html"><i class="fa fa-check"></i><b>8.6</b> Modelo con intercepto y pendiente aleatoria</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="sec-intercepto-pendiente-aleatorios.html"><a href="sec-intercepto-pendiente-aleatorios.html#sec-modelo-con-zona"><i class="fa fa-check"></i><b>8.6.1</b> Extensión con variable zona</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="sec-logistica-multinivel.html"><a href="sec-logistica-multinivel.html"><i class="fa fa-check"></i><b>8.7</b> Modelos logísticos multinivel</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="05-Categóricas.html"><a href="#modelo-nulo-log%C3%ADstico"><i class="fa fa-check"></i><b>8.7.1</b> Modelo nulo logístico</a></li>
<li class="chapter" data-level="8.7.2" data-path="05-Categóricas.html"><a href="#modelo-log%C3%ADstico-con-intercepto-aleatorio"><i class="fa fa-check"></i><b>8.7.2</b> Modelo logístico con intercepto aleatorio</a></li>
<li class="chapter" data-level="8.7.3" data-path="05-Categóricas.html"><a href="#modelo-log%C3%ADstico-con-intercepto-y-pendiente-aleatoria"><i class="fa fa-check"></i><b>8.7.3</b> Modelo logístico con intercepto y pendiente aleatoria</a></li>
<li class="chapter" data-level="8.7.4" data-path="05-Categóricas.html"><a href="#extensi%C3%B3n-con-variable-zona"><i class="fa fa-check"></i><b>8.7.4</b> Extensión con variable zona</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="cap-imputacion.html"><a href="cap-imputacion.html"><i class="fa fa-check"></i><b>9</b> Procedimientos de imputación</a>
<ul>
<li class="chapter" data-level="9.1" data-path="sec-mecanismos.html"><a href="sec-mecanismos.html"><i class="fa fa-check"></i><b>9.1</b> Mecanismos de datos faltantes</a></li>
<li class="chapter" data-level="9.2" data-path="sec-configuracion.html"><a href="sec-configuracion.html"><i class="fa fa-check"></i><b>9.2</b> Configuración de los datos de ejemplo</a></li>
<li class="chapter" data-level="9.3" data-path="sec-simulacion.html"><a href="sec-simulacion.html"><i class="fa fa-check"></i><b>9.3</b> Simulación de esquemas de datos faltantes</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="sec-simulacion.html"><a href="sec-simulacion.html#esquema-mcar"><i class="fa fa-check"></i><b>9.3.1</b> Esquema MCAR</a></li>
<li class="chapter" data-level="9.3.2" data-path="sec-simulacion.html"><a href="sec-simulacion.html#esquema-mar"><i class="fa fa-check"></i><b>9.3.2</b> Esquema MAR</a></li>
<li class="chapter" data-level="9.3.3" data-path="sec-simulacion.html"><a href="sec-simulacion.html#esquema-mnar"><i class="fa fa-check"></i><b>9.3.3</b> Esquema MNAR</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="sec-construccion-base.html"><a href="sec-construccion-base.html"><i class="fa fa-check"></i><b>9.4</b> Construcción de la base con datos faltantes</a></li>
<li class="chapter" data-level="9.5" data-path="sec-media-incondicional.html"><a href="sec-media-incondicional.html"><i class="fa fa-check"></i><b>9.5</b> Imputación por la media no condicional</a></li>
<li class="chapter" data-level="9.6" data-path="sec-media-condicional.html"><a href="sec-media-condicional.html"><i class="fa fa-check"></i><b>9.6</b> Imputación por la media condicional</a></li>
<li class="chapter" data-level="9.7" data-path="sec-hotdeck.html"><a href="sec-hotdeck.html"><i class="fa fa-check"></i><b>9.7</b> Imputación por hot-deck y cold-deck</a>
<ul>
<li class="chapter" data-level="9.7.1" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-hot-deck-para-el-ingreso"><i class="fa fa-check"></i><b>9.7.1</b> Imputación hot-deck para el ingreso</a></li>
<li class="chapter" data-level="9.7.2" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-hot-deck-para-la-variable-empleo"><i class="fa fa-check"></i><b>9.7.2</b> Imputación hot-deck para la variable empleo</a></li>
</ul></li>
<li class="chapter" data-level="9.8" data-path="sec-regresion.html"><a href="sec-regresion.html"><i class="fa fa-check"></i><b>9.8</b> Imputación por regresión</a></li>
<li class="chapter" data-level="9.9" data-path="sec-knn.html"><a href="sec-knn.html"><i class="fa fa-check"></i><b>9.9</b> Imputación por el vecino más cercano</a></li>
<li class="chapter" data-level="9.10" data-path="sec-knn-regresion.html"><a href="sec-knn-regresion.html"><i class="fa fa-check"></i><b>9.10</b> Imputación por el vecino más cercano con regresión</a></li>
<li class="chapter" data-level="9.11" data-path="sec-im.html"><a href="sec-im.html"><i class="fa fa-check"></i><b>9.11</b> Imputación múltiple</a>
<ul>
<li class="chapter" data-level="9.11.1" data-path="05-Categóricas.html"><a href="#estimadores-de-la-imputaci%C3%B3n-m%C3%BAltiple"><i class="fa fa-check"></i><b>9.11.1</b> Estimadores de la imputación múltiple</a></li>
<li class="chapter" data-level="9.11.2" data-path="05-Categóricas.html"><a href="#implementaci%C3%B3n-mediante-bootstrap"><i class="fa fa-check"></i><b>9.11.2</b> Implementación mediante bootstrap</a></li>
<li class="chapter" data-level="9.11.3" data-path="05-Categóricas.html"><a href="#imputaci%C3%B3n-m%C3%BAltiple-para-la-encuesta-de-hogares"><i class="fa fa-check"></i><b>9.11.3</b> Imputación múltiple para la encuesta de hogares</a></li>
<li class="chapter" data-level="9.11.4" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-del-ingreso-medio-mediante-imputaci%C3%B3n-m%C3%BAltiple"><i class="fa fa-check"></i><b>9.11.4</b> Estimación del ingreso medio mediante imputación múltiple</a></li>
<li class="chapter" data-level="9.11.5" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-la-varianza-del-ingreso"><i class="fa fa-check"></i><b>9.11.5</b> Estimación de la varianza del ingreso</a></li>
<li class="chapter" data-level="9.11.6" data-path="05-Categóricas.html"><a href="#estimaci%C3%B3n-de-proporciones-de-empleo"><i class="fa fa-check"></i><b>9.11.6</b> Estimación de proporciones de empleo</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a Análisis de encuestas de hogares con R </a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de encuestas con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tablas-cruzadas" class="section level2 hasAnchor" number="5.3">
<h2><span class="header-section-number">5.3</span> Tablas cruzadas<a href="tablas-cruzadas.html#tablas-cruzadas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En los levantamientos de encuestas de hogares, es habitual recopilar información sobre variables categóricas, que permiten clasificar a la población en grupos mutuamente excluyentes. Ejemplos comunes son el estado laboral (<em>ocupado</em>, <em>desempleado</em>, <em>inactivo</em>), el nivel educativo alcanzado (<em>primaria</em>, <em>secundaria</em>, <em>terciaria</em>) o el acceso a determinados servicios (<em>sí</em>, <em>no</em>). Explorar si dos de estas variables están asociadas constituye un elemento central del análisis, ya que ofrece información valiosa en distintos ámbitos:</p>
<ul>
<li>En política pública, al relacionar educación y empleo para diseñar estrategias laborales.</li>
<li>En evaluación de programas, al detectar variaciones en el acceso a salud según el nivel de ingresos.</li>
<li>En investigación social, al estudiar vínculos entre factores demográficos y servicios para comprender dinámicas y tendencias sociales.</li>
</ul>
<div id="definición-y-notación" class="section level3 hasAnchor" number="5.3.1">
<h3><span class="header-section-number">5.3.1</span> Definición y notación<a href="#definici%C3%B3n-y-notaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El estudio de la asociación entre dos variables categóricas implica verificar si la distribución de una depende de la otra. Para ello se comparan las frecuencias de todas las combinaciones posibles de categorías. Por ejemplo, puede contabilizarse cuántos individuos corresponden simultáneamente a cada nivel educativo y estado laboral. Estas frecuencias pueden transformarse en proporciones, que muestran la participación relativa de cada combinación en la población.</p>
<p>La herramienta más común para organizar esta información es la tabla de contingencia, también conocida como tabla cruzada. En su forma más simple, corresponde a una matriz de doble entrada en la que las filas representan las categorías de una variable y las columnas las de otra. Cada celda contiene la frecuencia o proporción de casos que presentan simultáneamente la combinación <span class="math inline">\((r,c)\)</span>.</p>
<p>Formalmente, sean <span class="math inline">\(x\)</span> y <span class="math inline">\(y\)</span> dos variables categóricas con <span class="math inline">\(R\)</span> y <span class="math inline">\(C\)</span> categorías respectivamente. Bajo un modelo de superpoblación, la distribución conjunta puede expresarse como:</p>
<p><span class="math display">\[
P_{rc} = Pr(X=r, Y=c), \quad r=1,\dots,R;\, c=1,\dots,C,
\]</span></p>
<p>con la restricción <span class="math inline">\(\sum_{r=1}^{R}\sum_{c=1}^{C} P_{rc}=1\)</span>.</p>
<p>Si se dispusiera de un censo, el número de unidades en cada celda <span class="math inline">\((r,c)\)</span> se calcularía como:</p>
<p><span class="math display">\[
N_{rc} = \sum_{h=1}^{H} \sum_{i \in U_{1h}} \sum_{k \in U_{hi}} I(x_{hik}=r, y_{hik}=c),
\]</span></p>
<p>y las proporciones poblacionales se definirían como <span class="math inline">\(p_{rc} = N_{rc}/N_{(++)}\)</span>, donde <span class="math inline">\(N_{(++)}\)</span> es el tamaño total de la población. En la práctica, al trabajar con encuestas, estas proporciones se estiman mediante estimadores ponderados teniendo en cuenta el diseño.</p>
</div>
<div id="tablas-de-doble-entrada" class="section level3 hasAnchor" number="5.3.2">
<h3><span class="header-section-number">5.3.2</span> Tablas de doble entrada<a href="tablas-cruzadas.html#tablas-de-doble-entrada" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una tabla de contingencia puede representarse en forma general como:</p>
<table>
<thead>
<tr class="header">
<th>Variable 2</th>
<th>Variable 1</th>
<th>Marginal fila</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>0</td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>0</td>
<td><span class="math inline">\(n_{00}\)</span></td>
<td><span class="math inline">\(n_{01}\)</span></td>
<td><span class="math inline">\(n_{0+}\)</span></td>
</tr>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(n_{10}\)</span></td>
<td><span class="math inline">\(n_{11}\)</span></td>
<td><span class="math inline">\(n_{1+}\)</span></td>
</tr>
<tr class="even">
<td>Marginal columna</td>
<td><span class="math inline">\(n_{+0}\)</span></td>
<td><span class="math inline">\(n_{+1}\)</span></td>
<td><span class="math inline">\(n_{++}\)</span></td>
</tr>
</tbody>
</table>
<p>Cuando se aplican los pesos muestrales, se obtienen las frecuencias ponderadas:</p>
<table>
<thead>
<tr class="header">
<th>Variable 2</th>
<th>Variable 1</th>
<th>Marginal fila</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>0</td>
<td>1</td>
<td></td>
</tr>
<tr class="even">
<td>0</td>
<td><span class="math inline">\(\hat{N}_{00}\)</span></td>
<td><span class="math inline">\(\hat{N}_{01}\)</span></td>
<td><span class="math inline">\(\hat{N}_{0+}\)</span></td>
</tr>
<tr class="odd">
<td>1</td>
<td><span class="math inline">\(\hat{N}_{10}\)</span></td>
<td><span class="math inline">\(\hat{N}_{11}\)</span></td>
<td><span class="math inline">\(\hat{N}_{1+}\)</span></td>
</tr>
<tr class="even">
<td>Marginal columna</td>
<td><span class="math inline">\(\hat{N}_{+0}\)</span></td>
<td><span class="math inline">\(\hat{N}_{+1}\)</span></td>
<td><span class="math inline">\(\hat{N}_{++}\)</span></td>
</tr>
</tbody>
</table>
<p>donde, por ejemplo, la frecuencia ponderada en la celda <span class="math inline">\((0,1)\)</span> está dada por:</p>
<p><span class="math display">\[
\hat{N}_{01} = \sum_{h=1}^{H} \sum_{\alpha=1}^{a_{h}} \sum_{i \in (0,1)}^{n_{h\alpha}} \omega_{h\alpha i}
\]</span></p>
<p>y las proporciones estimadas se calculan como:</p>
<p><span class="math display">\[
\hat{p}_{rc}=\frac{\hat{N}_{rc}}{\hat{N}_{++}}.
\]</span></p>
<p>Las tablas de contingencia suelen representarse como arreglos bidimensionales (<span class="math inline">\(R \times C\)</span>), pero pueden ampliarse para incluir una tercera variable o más, formando así <span class="math inline">\(L\)</span> subtablas que permiten analizar relaciones más complejas. Gracias a su simplicidad y potencia descriptiva, las tablas cruzadas son ampliamente utilizadas en la investigación aplicada y en el diseño de políticas públicas, ya que permiten identificar patrones y asociaciones que no serían evidentes a simple vista. Su interpretación también puede reforzarse mediante representaciones gráficas, como los diagramas de barras apiladas, que facilitan la visualización de tendencias y diferencias.</p>
</div>
<div id="proporciones-para-variables-binarias" class="section level3 hasAnchor" number="5.3.3">
<h3><span class="header-section-number">5.3.3</span> Proporciones para variables binarias<a href="tablas-cruzadas.html#proporciones-para-variables-binarias" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La estimación de una sola proporción, <span class="math inline">\(\pi\)</span>, para una variable de respuesta binaria requiere únicamente una extensión directa del estimador de razón. Al recodificar las categorías de respuesta originales en una variable indicadora <span class="math inline">\(y_{i}\)</span> con valores <span class="math inline">\(1\)</span> (presencia) y <span class="math inline">\(0\)</span> (ausencia), el estimador de la media de la razón estima la proporción o prevalencia <span class="math inline">\(\pi\)</span> en la población de la siguiente manera <span class="citation">(<a href="#ref-heeringa2017applied">Heeringa et al., 2017</a>)</span>:</p>
<p><span class="math display">\[
\hat{p} = \frac{\sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{n_{h\alpha}} \omega_{h\alpha i}I(y_{i}=1)}{\sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{n_{h\alpha}} \omega_{h\alpha i}}
= \frac{\hat{N}_{1}}{\hat{N}}.
\]</span></p>
<p>La varianza de este estimador puede aproximarse mediante la linealización de Taylor, así:</p>
<p><span class="math display">\[
v(\hat{p}) \dot{=} \frac{V(\hat{N}_{1})+\hat{p}^{2}V(\hat{N})-2\hat{p}\,cov(\hat{N}_{1},\hat{N})}{\hat{N}^{2}}.
\]</span></p>
<p>Cuando la proporción estimada se aproxima a 0 o 1, los intervalos de confianza estándar pueden producir límites fuera del rango <span class="math inline">\([0,1]\)</span>. Para solventar este problema, se proponen intervalos de confianza basados en transformaciones, como el <em>Wilson modificado</em> o el uso del <em>logit</em> de <span class="math inline">\(\hat{p}\)</span>, de la siguiente manera:</p>
<p><span class="math display">\[
IC[\text{logit}(\hat{p})] = \left\{ \ln\left(\frac{\hat{p}}{1-\hat{p}}\right) \pm \frac{t_{1-\alpha/2,gl}\,se(\hat{p})}{\hat{p}(1-\hat{p})}\right\},
\]</span></p>
<p>cuyo resultado puede transformarse de nuevo a la escala original de proporciones.</p>
</div>
<div id="proporciones-para-variables-multinomiales" class="section level3 hasAnchor" number="5.3.4">
<h3><span class="header-section-number">5.3.4</span> Proporciones para variables multinomiales<a href="tablas-cruzadas.html#proporciones-para-variables-multinomiales" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En encuestas, es común que las variables categóricas tengan más de dos categorías (multinomiales). En este caso, la estimación de la proporción para cada categoría <span class="math inline">\(k\)</span> sigue un esquema análogo:</p>
<p><span class="math display">\[
\hat{p}_{k} = \frac{\sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{n_{h\alpha}} \omega_{h\alpha i}I(y_{i}=k)}{\sum_{h=1}^{H}\sum_{\alpha=1}^{\alpha_{h}}\sum_{i=1}^{n_{h\alpha}} \omega_{h\alpha i}}
= \frac{\hat{N}_{k}}{\hat{N}}.
\]</span></p>
</div>
<div id="tablas-cruzadas-o-de-contingencia" class="section level3 hasAnchor" number="5.3.5">
<h3><span class="header-section-number">5.3.5</span> Tablas cruzadas o de contingencia<a href="tablas-cruzadas.html#tablas-cruzadas-o-de-contingencia" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cuando se analizan dos variables categóricas de manera conjunta, el objetivo es estudiar si existe asociación entre ellas. Para ello, se construyen tablas cruzadas (o tablas de contingencia), que organizan los datos en una matriz de <span class="math inline">\(R \times C\)</span>, donde <span class="math inline">\(R\)</span> son las categorías de la variable <span class="math inline">\(x\)</span> y <span class="math inline">\(C\)</span> las de la variable <span class="math inline">\(y\)</span>.</p>
<p>A diferencia de un simple conteo de casos, en encuestas se utilizan <strong>frecuencias ponderadas</strong> que reflejan la población total representada. Cada celda <span class="math inline">\((r,c)\)</span> contiene la frecuencia estimada:</p>
<p><span class="math display">\[
\hat{N}_{rc} = \sum_{h=1}^{H}\sum_{i \in s_{1h}}\sum_{k \in s_{hi}} w_{hik}\,I(x_{hik}=r; y_{hik}=c).
\]</span></p>
<p>Los totales marginales se obtienen como:</p>
<p><span class="math display">\[
\hat{N}_{(r+)} = \sum_{c} \hat{N}_{rc}, \quad \hat{N}_{(+c)} = \sum_{r} \hat{N}_{rc}, \quad \hat{N}_{(++)} = \sum_{r}\sum_{c} \hat{N}_{rc}.
\]</span></p>
<p>De estas frecuencias ponderadas se derivan <strong>proporciones conjuntas y marginales</strong>, que permiten analizar la distribución relativa de cada cruce:</p>
<p><span class="math display">\[
\hat{p}_{rc} = \frac{\hat{N}_{rc}}{\hat{N}_{++}}, \qquad
\hat{p}_{r+} = \frac{\hat{N}_{r+}}{\hat{N}_{++}}, \qquad
\hat{p}_{+c} = \frac{\hat{N}_{+c}}{\hat{N}_{++}}.
\]</span></p>
<p>Este enfoque ofrece una visión más completa de la relación entre categorías, ya que combina la estimación de proporciones simples con el análisis conjunto de distribuciones. Por ejemplo, se puede explorar cómo se distribuye el nivel educativo (filas) según la condición laboral (columnas), identificando patrones de desigualdad o brechas estructurales.</p>
<p>A continuación, siguiendo con la base de ejemplo, se estima la proporción de hombres y mujeres en pobreza y no pobreza junto con su error estándar e intervalos de confianza, como se muestra en la Tabla <a href="tablas-cruzadas.html#tab:tab-contingencia-pobreza-sexo">5.17</a>.</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="tablas-cruzadas.html#cb134-1" tabindex="-1"></a>dsg <span class="ot">&lt;-</span> diseno <span class="sc">%&gt;%</span> </span>
<span id="cb134-2"><a href="tablas-cruzadas.html#cb134-2" tabindex="-1"></a>       <span class="fu">mutate</span>(<span class="at">pobreza =</span> <span class="fu">factor</span>(pobreza, <span class="at">levels =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>,</span>
<span id="cb134-3"><a href="tablas-cruzadas.html#cb134-3" tabindex="-1"></a>                          <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;No pobre&quot;</span>, <span class="st">&quot;Pobre&quot;</span>))) </span></code></pre></div>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="tablas-cruzadas.html#cb135-1" tabindex="-1"></a>dsg <span class="sc">%&gt;%</span></span>
<span id="cb135-2"><a href="tablas-cruzadas.html#cb135-2" tabindex="-1"></a>  <span class="fu">group_by</span>(pobreza,Sex) <span class="sc">%&gt;%</span></span>
<span id="cb135-3"><a href="tablas-cruzadas.html#cb135-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">prop =</span> <span class="fu">survey_prop</span>(<span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb135-4"><a href="tablas-cruzadas.html#cb135-4" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-contingencia-pobreza-sexo">Cuadro 5.17: </span>Proporción de hombres y mujeres en condición de pobreza y no pobreza</caption>
<thead>
<tr class="header">
<th align="left">pobreza</th>
<th align="center">Sex</th>
<th align="center">prop</th>
<th align="center">prop_se</th>
<th align="center">prop_low</th>
<th align="center">prop_upp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">No pobre</td>
<td align="center">Female</td>
<td align="center">0.529</td>
<td align="center">0.012</td>
<td align="center">0.505</td>
<td align="center">0.554</td>
</tr>
<tr class="even">
<td align="left">No pobre</td>
<td align="center">Male</td>
<td align="center">0.471</td>
<td align="center">0.012</td>
<td align="center">0.446</td>
<td align="center">0.495</td>
</tr>
<tr class="odd">
<td align="left">Pobre</td>
<td align="center">Female</td>
<td align="center">0.524</td>
<td align="center">0.016</td>
<td align="center">0.492</td>
<td align="center">0.555</td>
</tr>
<tr class="even">
<td align="left">Pobre</td>
<td align="center">Male</td>
<td align="center">0.476</td>
<td align="center">0.016</td>
<td align="center">0.445</td>
<td align="center">0.508</td>
</tr>
</tbody>
</table>
<p>Como se puede observar, el 52.3% de las mujeres y el 47.6% son pobres. Generando intervalos de confianza al 95% de (49.2%, 55.5%) para las mujeres y (44.5%, 50.7%) para los hombres.</p>
<p>En la librería survey existe una alternativa para estimar tablas de contingencias y es utilizando la función <code>svyby</code> como se muestra a continuación, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-pobreza-sexo">5.18</a>:</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="tablas-cruzadas.html#cb136-1" tabindex="-1"></a>tab_Sex_Pobr <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Sex, <span class="at">by =</span>  <span class="sc">~</span>pobreza, <span class="at">design =</span> dsg, <span class="at">FUN =</span> svymean) </span></code></pre></div>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="tablas-cruzadas.html#cb137-1" tabindex="-1"></a>tab_Sex_Pobr <span class="sc">%&gt;%</span></span>
<span id="cb137-2"><a href="tablas-cruzadas.html#cb137-2" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-pobreza-sexo">Cuadro 5.18: </span>Proporción de hombres y mujeres por condición de pobreza (svyby)</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">pobreza</th>
<th align="center">SexFemale</th>
<th align="center">SexMale</th>
<th align="center">se.SexFemale</th>
<th align="center">se.SexMale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">No pobre</td>
<td align="left">No pobre</td>
<td align="center">0.529</td>
<td align="center">0.471</td>
<td align="center">0.012</td>
<td align="center">0.012</td>
</tr>
<tr class="even">
<td align="left">Pobre</td>
<td align="left">Pobre</td>
<td align="center">0.524</td>
<td align="center">0.476</td>
<td align="center">0.016</td>
<td align="center">0.016</td>
</tr>
</tbody>
</table>
<p>Como se pudo observar, los argumentos que requiere la función son definir la variable a la cual se desea estimar (formula), las categorías por la cual se desea estimar (by), el diseño muestral (desing) y el parámetro que se desea estimar (FUN). Para la estimación de los intervalos de confianza se utiliza la función <em>confint</em> como sigue:</p>
<p>Para la estimación de los intervalos de confianza se utiliza la función <code>confint</code>, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-confint-sexo-pobreza">5.19</a>:</p>
<div class="sourceCode" id="cb138"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb138-1"><a href="tablas-cruzadas.html#cb138-1" tabindex="-1"></a><span class="fu">confint</span>(tab_Sex_Pobr) <span class="sc">%&gt;%</span> </span>
<span id="cb138-2"><a href="tablas-cruzadas.html#cb138-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb138-3"><a href="tablas-cruzadas.html#cb138-3" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">&quot;Dominio&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb138-4"><a href="tablas-cruzadas.html#cb138-4" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-confint-sexo-pobreza">Cuadro 5.19: </span>Intervalos de confianza para la proporción por sexo y pobreza</caption>
<thead>
<tr class="header">
<th align="left">Dominio</th>
<th align="center">2.5 %</th>
<th align="center">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">No pobre:SexFemale</td>
<td align="center">0.505</td>
<td align="center">0.554</td>
</tr>
<tr class="even">
<td align="left">Pobre:SexFemale</td>
<td align="center">0.493</td>
<td align="center">0.555</td>
</tr>
<tr class="odd">
<td align="left">No pobre:SexMale</td>
<td align="center">0.446</td>
<td align="center">0.495</td>
</tr>
<tr class="even">
<td align="left">Pobre:SexMale</td>
<td align="center">0.445</td>
<td align="center">0.507</td>
</tr>
</tbody>
</table>
<p>Los cuales coinciden con los generados anteriormente usando la función <code>group_by</code>.</p>
<p>Otro análisis de interés relacionado con tablas de doble entrada en encuestas de hogares es estimar el porcentaje de desempleados por sexo, como se muestra en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-empleo-sexo">5.20</a>.</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="tablas-cruzadas.html#cb139-1" tabindex="-1"></a>tab_Sex_Ocupa <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>Sex, <span class="at">by =</span> <span class="sc">~</span>Employment,</span>
<span id="cb139-2"><a href="tablas-cruzadas.html#cb139-2" tabindex="-1"></a>                       <span class="at">design =</span> diseno, <span class="at">FUN =</span> svymean)</span></code></pre></div>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="tablas-cruzadas.html#cb140-1" tabindex="-1"></a>tab_Sex_Ocupa <span class="sc">%&gt;%</span></span>
<span id="cb140-2"><a href="tablas-cruzadas.html#cb140-2" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-empleo-sexo">Cuadro 5.20: </span>Proporción de hombres y mujeres por estado de ocupación (svyby)</caption>
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="13%" />
<col width="20%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Employment</th>
<th align="center">SexFemale</th>
<th align="center">SexMale</th>
<th align="center">se.SexFemale</th>
<th align="center">se.SexMale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Unemployed</td>
<td align="left">Unemployed</td>
<td align="center">0.273</td>
<td align="center">0.727</td>
<td align="center">0.054</td>
<td align="center">0.054</td>
</tr>
<tr class="even">
<td align="left">Inactive</td>
<td align="left">Inactive</td>
<td align="center">0.770</td>
<td align="center">0.230</td>
<td align="center">0.023</td>
<td align="center">0.023</td>
</tr>
<tr class="odd">
<td align="left">Employed</td>
<td align="left">Employed</td>
<td align="center">0.405</td>
<td align="center">0.595</td>
<td align="center">0.019</td>
<td align="center">0.019</td>
</tr>
</tbody>
</table>
<p>De la anterior salida se puede observar que, el 27.2% de las mujeres y el 72.7% de los hombres están desempleados con errores estándares para estas estimaciones de 5.3% para mujeres y hombres. cuyos intervalos de confianza se calculan a continuación, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-confint-empleo-sexo">5.21</a>:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="tablas-cruzadas.html#cb141-1" tabindex="-1"></a><span class="fu">confint</span>(tab_Sex_Ocupa) <span class="sc">%&gt;%</span> </span>
<span id="cb141-2"><a href="tablas-cruzadas.html#cb141-2" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb141-3"><a href="tablas-cruzadas.html#cb141-3" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="st">&quot;Dominio&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb141-4"><a href="tablas-cruzadas.html#cb141-4" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-confint-empleo-sexo">Cuadro 5.21: </span>Intervalos de confianza para la proporción por sexo y ocupación</caption>
<thead>
<tr class="header">
<th align="left">Dominio</th>
<th align="center">2.5 %</th>
<th align="center">97.5 %</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Unemployed:SexFemale</td>
<td align="center">0.168</td>
<td align="center">0.378</td>
</tr>
<tr class="even">
<td align="left">Inactive:SexFemale</td>
<td align="center">0.724</td>
<td align="center">0.816</td>
</tr>
<tr class="odd">
<td align="left">Employed:SexFemale</td>
<td align="center">0.369</td>
<td align="center">0.441</td>
</tr>
<tr class="even">
<td align="left">Unemployed:SexMale</td>
<td align="center">0.622</td>
<td align="center">0.832</td>
</tr>
<tr class="odd">
<td align="left">Inactive:SexMale</td>
<td align="center">0.184</td>
<td align="center">0.276</td>
</tr>
<tr class="even">
<td align="left">Employed:SexMale</td>
<td align="center">0.559</td>
<td align="center">0.631</td>
</tr>
</tbody>
</table>
<p>Si ahora el objetivo es estimar la pobreza, pero por las distintas regiones que se tienen en la base de datos. Primero, dado que la variable <em>pobreza</em> es de tipo numérica, es necesario convertirla en factor y luego realizar la estimación con la función <code>svyby</code>, como se muestra en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-region-pobreza">5.22</a>.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="tablas-cruzadas.html#cb142-1" tabindex="-1"></a>tab_region_pobreza <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span><span class="fu">as.factor</span>(pobreza),  <span class="at">by =</span> <span class="sc">~</span>Region,</span>
<span id="cb142-2"><a href="tablas-cruzadas.html#cb142-2" tabindex="-1"></a>                            <span class="at">design =</span>  diseno, <span class="at">FUN =</span> svymean)</span>
<span id="cb142-3"><a href="tablas-cruzadas.html#cb142-3" tabindex="-1"></a>tab_region_pobreza <span class="sc">%&gt;%</span></span>
<span id="cb142-4"><a href="tablas-cruzadas.html#cb142-4" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-region-pobreza">Cuadro 5.22: </span>Proporción en condición de pobreza por región</caption>
<colgroup>
<col width="9%" />
<col width="9%" />
<col width="19%" />
<col width="19%" />
<col width="21%" />
<col width="21%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Region</th>
<th align="center">as.factor(pobreza)0</th>
<th align="center">as.factor(pobreza)1</th>
<th align="center">se.as.factor(pobreza)0</th>
<th align="center">se.as.factor(pobreza)1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Norte</td>
<td align="left">Norte</td>
<td align="center">0.641</td>
<td align="center">0.359</td>
<td align="center">0.055</td>
<td align="center">0.055</td>
</tr>
<tr class="even">
<td align="left">Sur</td>
<td align="left">Sur</td>
<td align="center">0.656</td>
<td align="center">0.344</td>
<td align="center">0.043</td>
<td align="center">0.043</td>
</tr>
<tr class="odd">
<td align="left">Centro</td>
<td align="left">Centro</td>
<td align="center">0.635</td>
<td align="center">0.365</td>
<td align="center">0.079</td>
<td align="center">0.079</td>
</tr>
<tr class="even">
<td align="left">Occidente</td>
<td align="left">Occidente</td>
<td align="center">0.599</td>
<td align="center">0.401</td>
<td align="center">0.047</td>
<td align="center">0.047</td>
</tr>
<tr class="odd">
<td align="left">Oriente</td>
<td align="left">Oriente</td>
<td align="center">0.548</td>
<td align="center">0.452</td>
<td align="center">0.088</td>
<td align="center">0.088</td>
</tr>
</tbody>
</table>
<p>De lo anterior se puede concluir que, en la región Norte, el 35% de las personas están en estado de pobreza mientras que en el sur es el 34%. La pobreza más alta se tiene en la región oriente con un 45% de pobres. Los errores estándares de las estimaciones.</p>
</div>
<div id="prueba-de-independencia-chi2" class="section level3 hasAnchor" number="5.3.6">
<h3><span class="header-section-number">5.3.6</span> Prueba de independencia <span class="math inline">\(\chi^{2}\)</span><a href="tablas-cruzadas.html#prueba-de-independencia-chi2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Una <strong>prueba de hipótesis</strong> es un procedimiento estadístico que permite evaluar la validez de una afirmación sobre una población, comparando la evidencia empírica de una muestra con lo que se esperaría si dicha afirmación fuera cierta. En el caso de las <strong>pruebas de independencia</strong>, se plantea como hipótesis nula (<span class="math inline">\(H_{0}\)</span>) que dos variables categóricas son independientes, es decir, que la distribución de una no depende de las categorías de la otra. Matemáticamente, esta hipótesis puede expresarse como:</p>
<p><span class="math display">\[
H_0: P_{rc}^0 = P_{r+} \times P_{+c}, \quad \text{para todo } r = 1,\ldots,R \text{ y } c = 1,\ldots,C
\]</span></p>
<p>donde <span class="math inline">\(P_{rc}^0\)</span> representa la proporción esperada en la celda <span class="math inline">\((r,c)\)</span> bajo independencia, y <span class="math inline">\(P_{r+}\)</span> y <span class="math inline">\(P_{+c}\)</span> las proporciones marginales de las filas y columnas, respectivamente.</p>
<p>En consecuencia, la prueba consiste en contrastar las proporciones estimadas <span class="math inline">\(\hat{p}*{rc}\)</span> con las esperadas <span class="math inline">\(P*{rc}^0\)</span>. Cuando las diferencias son pequeñas, los datos respaldan la hipótesis nula; en cambio, discrepancias significativas conducen al rechazo de <span class="math inline">\(H_0\)</span>.</p>
<div id="prueba-chi2-clásica" class="section level4 hasAnchor" number="5.3.6.1">
<h4><span class="header-section-number">5.3.6.1</span> Prueba <span class="math inline">\(\chi^{2}\)</span> clásica<a href="#prueba-chi2-cl%C3%A1sica" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Para una tabla de <span class="math inline">\(2 \times 2\)</span>, la estadística de Pearson se define como:</p>
<p><span class="math display">\[
\chi^{2}  =  n_{++}\sum_{r}\sum_{c}\frac{\left(p_{rc}-\hat{\pi}_{rc}\right)^{2}}{\hat{\pi}_{rc}}
\]</span></p>
<p>donde <span class="math inline">\(\hat{\pi}*{rc}=\frac{n*{r+}}{n_{++}} \cdot \frac{n_{+c}}{n_{++}}\)</span> corresponde a las proporciones esperadas bajo independencia.</p>
<p>En términos prácticos, las <strong>tablas de contingencia ponderadas</strong> constituyen el insumo de la prueba, ya que cada celda <span class="math inline">\(\hat{N}_{rc}\)</span> estima el número de personas en la población en esa combinación de categorías. A partir de ellas se calculan frecuencias relativas y se evalúa la independencia de las variables.</p>
</div>
<div id="ajustes-para-encuestas-prueba-de-rao-scott" class="section level4 hasAnchor" number="5.3.6.2">
<h4><span class="header-section-number">5.3.6.2</span> Ajustes para encuestas: prueba de Rao-Scott<a href="tablas-cruzadas.html#ajustes-para-encuestas-prueba-de-rao-scott" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>En encuestas de hogares, el análisis es más complejo porque el diseño muestral (estratificación, conglomerados y ponderación) altera la varianza de los estimadores. Por ello, la prueba <span class="math inline">\(\chi^{2}\)</span> debe ajustarse para reflejar estas particularidades.</p>
<p>El <strong>ajuste de Rao-Scott</strong> <span class="citation">(<a href="#ref-rao1984chisquare">Rao &amp; Scott, 1984</a>; <a href="#ref-thomas1987chisquare">Thomas &amp; Rao, 1987</a>)</span> corrige la prueba clásica mediante el <strong>efecto de diseño generalizado (GDEFF)</strong>, lo que produce un estadístico robusto:</p>
<p><span class="math display">\[
X_{RS}^2 = \frac{n_{++}}{GDEFF} \sum_r \sum_c \frac{(\hat{p}_{rc} - \hat{P}_{rc}^0)^2}{\hat{P}_{rc}^0}
\]</span></p>
<p>Bajo <span class="math inline">\(H_0\)</span>, <span class="math inline">\(X_{RS}^2\)</span> sigue aproximadamente una distribución <span class="math inline">\(\chi^2\)</span> con <span class="math inline">\((R-1)(C-1)\)</span> grados de libertad. En casos de <strong>muestras pequeñas</strong>, es común aplicar ajustes basados en la distribución F, que mejoran la precisión de los resultados. Actualmente, las pruebas de Rao-Scott constituyen el estándar en el análisis de datos categóricos en encuestas complejas <span class="citation">(<a href="#ref-heeringa2017applied">Heeringa et al., 2017</a>)</span>.</p>
</div>
<div id="ejemplo-en-r" class="section level4 hasAnchor" number="5.3.6.3">
<h4><span class="header-section-number">5.3.6.3</span> Ejemplo en R<a href="tablas-cruzadas.html#ejemplo-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>El paquete <strong><code>survey</code></strong> en R implementa estas pruebas a través de la función <code>svychisq()</code>, que aplica automáticamente las correcciones de Rao-Scott. A modo de ejemplo, para evaluar si la pobreza es independiente del sexo, se ejecuta:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="tablas-cruzadas.html#cb143-1" tabindex="-1"></a><span class="fu">svychisq</span>(<span class="at">formula =</span> <span class="sc">~</span>Sex <span class="sc">+</span> pobreza, <span class="at">design =</span> diseno, <span class="at">statistic=</span><span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  NextMethod()
## F = 0.056464, ndf = 1, ddf = 119, p-value = 0.8126</code></pre>
<ul>
<li>Si el <strong>p-valor</strong> es superior al 5%, no se rechaza <span class="math inline">\(H_0\)</span>, concluyendo que no existe evidencia de asociación entre pobreza y sexo.</li>
<li>Si el <strong>p-valor</strong> es inferior al 5%, se rechaza <span class="math inline">\(H_0\)</span>, lo que sugiere dependencia entre las variables.</li>
</ul>
<p>De manera similar, se pueden evaluar otras relaciones, como desempleo y sexo o pobreza y región:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="tablas-cruzadas.html#cb145-1" tabindex="-1"></a><span class="fu">svychisq</span>(<span class="at">formula =</span> <span class="sc">~</span>Sex <span class="sc">+</span> Employment, <span class="at">design =</span> diseno, <span class="at">statistic =</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  NextMethod()
## F = 62.251, ndf = 1.6865, ddf = 200.6978, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="tablas-cruzadas.html#cb147-1" tabindex="-1"></a><span class="fu">svychisq</span>(<span class="at">formula =</span> <span class="sc">~</span>Region <span class="sc">+</span> pobreza, <span class="at">design =</span> diseno, <span class="at">statistic =</span> <span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s X^2: Rao &amp; Scott adjustment
## 
## data:  NextMethod()
## F = 0.48794, ndf = 3.0082, ddf = 357.9731, p-value = 0.6914</code></pre>
<p><strong>Razón de odds</strong></p>
<p>La traducción más aproximada del término <em>odds</em> es “la ventaja”: en términos de probabilidades, expresa cuánto más probable es que ocurra un evento frente a que no ocurra. También se puede utilizar para cuantificar la asociación entre los niveles de una variable y un factor categórico <span class="citation">(<a href="#ref-heeringa2017applied">Heeringa et al., 2017</a>)</span>.</p>
<p>Suponga que se desea calcular la siguiente razón de odds.</p>
<p><span class="math display">\[
\frac{\frac{P(Sex = Female \mid pobreza = 0 )}{P(Sex = Female \mid pobreza = 1 )}}{
\frac{P(Sex = Male \mid pobreza = 1 )}{P(Sex = Male \mid pobreza = 0 )}
}
\]</span></p>
<p>El procedimiento para realizarlo en <code>R</code> sería, primero estimar las proporciones de la tabla cruzada entre las variables sexo y pobreza, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-interaccion-sexo-pobreza">5.23</a>:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="tablas-cruzadas.html#cb149-1" tabindex="-1"></a>tab_Sex_Pobr <span class="ot">&lt;-</span> <span class="fu">svymean</span>(<span class="at">x =</span> <span class="sc">~</span><span class="fu">interaction</span> (Sex, pobreza), <span class="at">design =</span> diseno, </span>
<span id="cb149-2"><a href="tablas-cruzadas.html#cb149-2" tabindex="-1"></a>                        <span class="at">se=</span>T, <span class="at">na.rm=</span>T, <span class="at">ci=</span>T, <span class="at">keep.vars=</span>T)</span></code></pre></div>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="tablas-cruzadas.html#cb150-1" tabindex="-1"></a>tab_Sex_Pobr <span class="sc">%&gt;%</span> <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb150-2"><a href="tablas-cruzadas.html#cb150-2" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-interaccion-sexo-pobreza">Cuadro 5.23: </span>Proporciones conjuntas de sexo y condición de pobreza</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">mean</th>
<th align="center">SE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">interaction(Sex, pobreza)Female.0</td>
<td align="left">0.322</td>
<td align="center">0.018</td>
</tr>
<tr class="even">
<td align="left">interaction(Sex, pobreza)Male.0</td>
<td align="left">0.286</td>
<td align="center">0.018</td>
</tr>
<tr class="odd">
<td align="left">interaction(Sex, pobreza)Female.1</td>
<td align="left">0.205</td>
<td align="center">0.017</td>
</tr>
<tr class="even">
<td align="left">interaction(Sex, pobreza)Male.1</td>
<td align="left">0.187</td>
<td align="center">0.018</td>
</tr>
</tbody>
</table>
<p>Luego, se realiza el contraste dividiendo cada uno de los elementos de la expresión mostrada anteriormente:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="tablas-cruzadas.html#cb151-1" tabindex="-1"></a><span class="fu">svycontrast</span>(<span class="at">stat =</span> tab_Sex_Pobr, </span>
<span id="cb151-2"><a href="tablas-cruzadas.html#cb151-2" tabindex="-1"></a><span class="at">contrasts =</span> <span class="fu">quote</span>((<span class="st">`</span><span class="at">interaction(Sex, pobreza)Female.0</span><span class="st">`</span><span class="sc">/</span><span class="st">`</span><span class="at">interaction(Sex, pobreza)Female.1</span><span class="st">`</span>) <span class="sc">/</span>(<span class="st">`</span><span class="at">interaction(Sex, pobreza)Male.0</span><span class="st">`</span><span class="sc">/</span> <span class="st">`</span><span class="at">interaction(Sex, pobreza)Male.1</span><span class="st">`</span>)))</span></code></pre></div>
<pre><code>##           nlcon     SE
## contrast 1.0226 0.0961</code></pre>
<p>Obteniendo que, se estima que el odds de las mujeres que no están en estado de pobreza es 1.02 comparándolo con el odds de los hombres. En otras palabras, se estima que las probabilidades de que las mujeres no estén en estado de pobreza sin tener en cuenta ninguna otra variable de la encuesta es cerca de 2% mayor que las probabilidades de los hombres.</p>
<p><strong>Diferencia de proporciones en tablas de contingencias</strong></p>
<p>Según <span class="citation">Heeringa et al. (<a href="#ref-heeringa2017applied">2017</a>)</span>, las estimaciones de las proporciones de las filas en las tablas de doble entrada son, de hecho, estimaciones de subpoblaciones en las que la subpoblación se define por los niveles de la variable factorial. Ahora bien, si el interés se centra en estimar diferencias de las proporciones de las categorías entre dos niveles de una variable factorial, se pueden usar contrastes.</p>
<p>A manera de ejemplo, se requiere estimar ahora, el contraste de proporciones de mujeres en estado de pobreza versus los hombres en esta misma condición (<span class="math inline">\(\hat{p}_F - \hat{p}_M\)</span>). Para ellos, primero, estimemos la proporción de hombres y mujeres en estado de pobreza como se ha mostrado en capítulos anteriores, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-pobreza-sexo2">5.24</a>:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="tablas-cruzadas.html#cb153-1" tabindex="-1"></a>tab_sex_pobreza <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>pobreza, <span class="at">by =</span> <span class="sc">~</span>Sex,</span>
<span id="cb153-2"><a href="tablas-cruzadas.html#cb153-2" tabindex="-1"></a>                         <span class="at">design =</span> diseno, svymean, <span class="at">na.rm=</span>T,</span>
<span id="cb153-3"><a href="tablas-cruzadas.html#cb153-3" tabindex="-1"></a>                         <span class="at">covmat =</span> <span class="cn">TRUE</span>, <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb153-4"><a href="tablas-cruzadas.html#cb153-4" tabindex="-1"></a>tab_sex_pobreza <span class="sc">%&gt;%</span></span>
<span id="cb153-5"><a href="tablas-cruzadas.html#cb153-5" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-pobreza-sexo2">Cuadro 5.24: </span>Proporción en condición de pobreza por sexo</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Sex</th>
<th align="center">pobreza</th>
<th align="center">se</th>
<th align="center">ci_l</th>
<th align="center">ci_u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Female</td>
<td align="center">0.389</td>
<td align="center">0.032</td>
<td align="center">0.327</td>
<td align="center">0.451</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Male</td>
<td align="center">0.395</td>
<td align="center">0.037</td>
<td align="center">0.323</td>
<td align="center">0.466</td>
</tr>
</tbody>
</table>
<p>Ahora bien, para calcular la estimación de la diferencia de proporciones junto con sus errores estándares, se realizarán los siguientes pasos:</p>
<ul>
<li><em>Paso 1:</em> Calcular la diferencia de estimaciones</li>
</ul>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="tablas-cruzadas.html#cb154-1" tabindex="-1"></a><span class="fl">0.3892</span> <span class="sc">-</span> <span class="fl">0.3946</span>          </span></code></pre></div>
<pre><code>## [1] -0.0054</code></pre>
<p>Con la función <code>vcov</code> se obtiene la matriz de covarianzas, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-vcov-sex-pobreza">5.25</a>:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="tablas-cruzadas.html#cb156-1" tabindex="-1"></a><span class="fu">vcov</span>(tab_sex_pobreza) <span class="sc">%&gt;%</span></span>
<span id="cb156-2"><a href="tablas-cruzadas.html#cb156-2" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb156-3"><a href="tablas-cruzadas.html#cb156-3" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>(<span class="at">digits =</span> <span class="dv">10</span>)</span></code></pre></div>
<table>
<caption><span id="tab:tab-vcov-sex-pobreza">Cuadro 5.25: </span>Matriz de varianzas y covarianzas de la proporción de pobreza por sexo</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Female</th>
<th align="center">Male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">0.0009982953</td>
<td align="center">0.0009182927</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">0.0009182927</td>
<td align="center">0.0013415823</td>
</tr>
</tbody>
</table>
<ul>
<li><em>Paso 2:</em> El cálculo del error estándar es:</li>
</ul>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="tablas-cruzadas.html#cb157-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">0.0009983</span> <span class="sc">+</span> <span class="fl">0.0013416</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.0009183</span>)</span></code></pre></div>
<pre><code>## [1] 0.02243435</code></pre>
<p>Ahora bien, aplicando la función <code>svycontrast</code> se puede obtener la estimación de la diferencia de proporciones anterior:</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="tablas-cruzadas.html#cb159-1" tabindex="-1"></a><span class="fu">svycontrast</span>(tab_sex_pobreza,</span>
<span id="cb159-2"><a href="tablas-cruzadas.html#cb159-2" tabindex="-1"></a>            <span class="fu">list</span>(<span class="at">diff_Sex =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb159-3"><a href="tablas-cruzadas.html#cb159-3" tabindex="-1"></a>  <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##              contrast   diff_Sex
## diff_Sex -0.005322297 0.02243418</code></pre>
<p>De lo que se concluye que, la diferencia entre las proporciones de mujeres y hombres en estado de pobreza es -0.005 (-0.5%) con una desviación estándar de 0.022.</p>
<p>Otro ejercicio de interés en un análisis de encuestas de hogares es verificar la diferencia del desempleo por sexo. Al igual que el ejemplo anterior, se inicia con la estimación del porcentaje de desempleados por sexo, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-desempleo-sexo">5.26</a>:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="tablas-cruzadas.html#cb161-1" tabindex="-1"></a>tab_sex_desempleo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>desempleo, <span class="at">by =</span> <span class="sc">~</span>Sex,</span>
<span id="cb161-2"><a href="tablas-cruzadas.html#cb161-2" tabindex="-1"></a>                           <span class="at">design  =</span> diseno <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(desempleo)),</span>
<span id="cb161-3"><a href="tablas-cruzadas.html#cb161-3" tabindex="-1"></a>                           <span class="at">FUN     =</span> svymean, <span class="at">na.rm=</span>T, <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb161-4"><a href="tablas-cruzadas.html#cb161-4" tabindex="-1"></a>                           <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb161-5"><a href="tablas-cruzadas.html#cb161-5" tabindex="-1"></a>tab_sex_desempleo <span class="sc">%&gt;%</span></span>
<span id="cb161-6"><a href="tablas-cruzadas.html#cb161-6" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-desempleo-sexo">Cuadro 5.26: </span>Proporción en condición de desempleo por sexo</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Sex</th>
<th align="center">desempleo</th>
<th align="center">se</th>
<th align="center">ci_l</th>
<th align="center">ci_u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">Female</td>
<td align="center">0.022</td>
<td align="center">0.006</td>
<td align="center">0.011</td>
<td align="center">0.033</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">Male</td>
<td align="center">0.068</td>
<td align="center">0.012</td>
<td align="center">0.044</td>
<td align="center">0.092</td>
</tr>
</tbody>
</table>
<p>Para calcular la estimación de la diferencia de proporciones junto con sus errores estándares, se realizarán los siguientes pasos:</p>
<ul>
<li><em>Paso 1</em>: Diferencia de las estimaciones</li>
</ul>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="tablas-cruzadas.html#cb162-1" tabindex="-1"></a><span class="fl">0.02169</span> <span class="sc">-</span> <span class="fl">0.06783</span>   </span></code></pre></div>
<pre><code>## [1] -0.04614</code></pre>
<p>Estimación de la matriz de covarianza, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-vcov-sex-desempleo">5.27</a>:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="tablas-cruzadas.html#cb164-1" tabindex="-1"></a><span class="fu">vcov</span>(tab_sex_desempleo) <span class="sc">%&gt;%</span></span>
<span id="cb164-2"><a href="tablas-cruzadas.html#cb164-2" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb164-3"><a href="tablas-cruzadas.html#cb164-3" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>(<span class="at">digits =</span> <span class="dv">10</span>)</span></code></pre></div>
<table>
<caption><span id="tab:tab-vcov-sex-desempleo">Cuadro 5.27: </span>Matriz de varianzas y covarianzas de la proporción de desempleo por sexo</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Female</th>
<th align="center">Male</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Female</td>
<td align="left">3.11369e-05</td>
<td align="center">0.0000208130</td>
</tr>
<tr class="even">
<td align="left">Male</td>
<td align="left">2.08130e-05</td>
<td align="center">0.0001478933</td>
</tr>
</tbody>
</table>
<ul>
<li><em>Paso 2</em>: Estimación del error estándar.</li>
</ul>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="tablas-cruzadas.html#cb165-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">0.00003114</span>  <span class="sc">+</span> <span class="fl">0.00014789</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.00002081</span>)</span></code></pre></div>
<pre><code>## [1] 0.0117222</code></pre>
<p>Siguiendo el ejemplo anterior, utilizando la función <code>svycontrast</code> se tiene que:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="tablas-cruzadas.html#cb167-1" tabindex="-1"></a><span class="fu">svycontrast</span>(tab_sex_desempleo,</span>
<span id="cb167-2"><a href="tablas-cruzadas.html#cb167-2" tabindex="-1"></a>            <span class="fu">list</span>(<span class="at">diff_Sex =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb167-3"><a href="tablas-cruzadas.html#cb167-3" tabindex="-1"></a>  <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##            contrast   diff_Sex
## diff_Sex 0.04613982 0.01172195</code></pre>
<p>de lo que se concluye que, la estimación del contraste es 0.04 (4%) con un error estándar de 0.011.</p>
<p>Otro ejercicio que se puede realizar en una encuesta de hogares es ahora estimar la proporción de desempleados por región. Para la realización de este ejercicio, se seguirán los pasos de los dos ejemplos anteriores, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-desempleo-region">5.28</a>:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="tablas-cruzadas.html#cb169-1" tabindex="-1"></a>tab_region_desempleo <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span>  <span class="sc">~</span>desempleo, <span class="at">by =</span> <span class="sc">~</span>Region,</span>
<span id="cb169-2"><a href="tablas-cruzadas.html#cb169-2" tabindex="-1"></a>                              <span class="at">design  =</span> diseno <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(desempleo)),</span>
<span id="cb169-3"><a href="tablas-cruzadas.html#cb169-3" tabindex="-1"></a>                              <span class="at">FUN     =</span> svymean, <span class="at">na.rm=</span>T, <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb169-4"><a href="tablas-cruzadas.html#cb169-4" tabindex="-1"></a>                              <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb169-5"><a href="tablas-cruzadas.html#cb169-5" tabindex="-1"></a>tab_region_desempleo <span class="sc">%&gt;%</span></span>
<span id="cb169-6"><a href="tablas-cruzadas.html#cb169-6" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-desempleo-region">Cuadro 5.28: </span>Proporción en condición de desempleo por región</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Region</th>
<th align="center">desempleo</th>
<th align="center">se</th>
<th align="center">ci_l</th>
<th align="center">ci_u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Norte</td>
<td align="left">Norte</td>
<td align="center">0.049</td>
<td align="center">0.020</td>
<td align="center">0.010</td>
<td align="center">0.088</td>
</tr>
<tr class="even">
<td align="left">Sur</td>
<td align="left">Sur</td>
<td align="center">0.066</td>
<td align="center">0.024</td>
<td align="center">0.019</td>
<td align="center">0.112</td>
</tr>
<tr class="odd">
<td align="left">Centro</td>
<td align="left">Centro</td>
<td align="center">0.039</td>
<td align="center">0.012</td>
<td align="center">0.014</td>
<td align="center">0.063</td>
</tr>
<tr class="even">
<td align="left">Occidente</td>
<td align="left">Occidente</td>
<td align="center">0.040</td>
<td align="center">0.012</td>
<td align="center">0.016</td>
<td align="center">0.064</td>
</tr>
<tr class="odd">
<td align="left">Oriente</td>
<td align="left">Oriente</td>
<td align="center">0.030</td>
<td align="center">0.013</td>
<td align="center">0.005</td>
<td align="center">0.054</td>
</tr>
</tbody>
</table>
<p>Ahora, el interés es realizar los contrastes siguientes para desempleo:</p>
<p><span class="math inline">\(\hat{p}_{Norte} - \hat{p}_{Centro} = 0.01004\)</span>,
<span class="math inline">\(\hat{p}_{Sur} - \hat{p}_{Centro} = 0.02691\)</span><br />
<span class="math inline">\(\hat{p}_{Occidente} - \hat{p}_{Oriente} = 0.01046\)</span></p>
<p>Escrita de forma matricial sería:</p>
<p><span class="math display">\[
\left[\begin{array}{ccccc}
1 &amp; 0 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{array}\right]
\]</span></p>
<p>La matriz de varianzas y covarianzas es:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="tablas-cruzadas.html#cb170-1" tabindex="-1"></a><span class="fu">vcov</span>(tab_region_desempleo) <span class="sc">%&gt;%</span></span>
<span id="cb170-2"><a href="tablas-cruzadas.html#cb170-2" tabindex="-1"></a>  <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb170-3"><a href="tablas-cruzadas.html#cb170-3" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<p>Por tanto, la varianza estimada está dada por:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="tablas-cruzadas.html#cb171-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">0.0002981</span> <span class="sc">+</span> <span class="fl">0.0002884</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 0.02421776</code></pre>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="tablas-cruzadas.html#cb173-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">0.0001968</span> <span class="sc">+</span> <span class="fl">0.0002884</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 0.02202726</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="tablas-cruzadas.html#cb175-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">0.0001267</span> <span class="sc">+</span> <span class="fl">0.0004093</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="dv">0</span>)</span></code></pre></div>
<pre><code>## [1] 0.02315167</code></pre>
<p>Usando la función <code>svycontrast</code>, la estimación de los contrastes sería:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="tablas-cruzadas.html#cb177-1" tabindex="-1"></a><span class="fu">svycontrast</span>(tab_region_desempleo, <span class="fu">list</span>(</span>
<span id="cb177-2"><a href="tablas-cruzadas.html#cb177-2" tabindex="-1"></a>                             <span class="at">Norte_sur =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb177-3"><a href="tablas-cruzadas.html#cb177-3" tabindex="-1"></a>                             <span class="at">Sur_centro =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb177-4"><a href="tablas-cruzadas.html#cb177-4" tabindex="-1"></a>                             <span class="at">Occidente_Oriente =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##                     contrast         SE
## Norte_sur         0.01004463 0.02355327
## Sur_centro        0.02690618 0.02679477
## Occidente_Oriente 0.01046292 0.01758365</code></pre>
<p>Por último, repitiendo el contraste anterior y los pasos para resolverlo, pero ahora utilizando la variable pobreza se tiene, presentada en la Tabla <a href="tablas-cruzadas.html#tab:tab-svyby-pobreza-region">5.29</a>:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="tablas-cruzadas.html#cb179-1" tabindex="-1"></a>tab_region_pobreza <span class="ot">&lt;-</span> <span class="fu">svyby</span>(<span class="at">formula =</span> <span class="sc">~</span>pobreza, <span class="at">by =</span> <span class="sc">~</span>Region,</span>
<span id="cb179-2"><a href="tablas-cruzadas.html#cb179-2" tabindex="-1"></a>                            <span class="at">design =</span> diseno <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(desempleo)),</span>
<span id="cb179-3"><a href="tablas-cruzadas.html#cb179-3" tabindex="-1"></a>                            <span class="at">FUN =</span> svymean, <span class="at">na.rm=</span>T, <span class="at">covmat =</span> <span class="cn">TRUE</span>,</span>
<span id="cb179-4"><a href="tablas-cruzadas.html#cb179-4" tabindex="-1"></a>                            <span class="at">vartype =</span> <span class="fu">c</span>(<span class="st">&quot;se&quot;</span>, <span class="st">&quot;ci&quot;</span>))</span>
<span id="cb179-5"><a href="tablas-cruzadas.html#cb179-5" tabindex="-1"></a>tab_region_pobreza <span class="sc">%&gt;%</span></span>
<span id="cb179-6"><a href="tablas-cruzadas.html#cb179-6" tabindex="-1"></a>  <span class="fu">tabla_fmt</span>()</span></code></pre></div>
<table>
<caption><span id="tab:tab-svyby-pobreza-region">Cuadro 5.29: </span>Proporción en condición de pobreza por región</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="left">Region</th>
<th align="center">pobreza</th>
<th align="center">se</th>
<th align="center">ci_l</th>
<th align="center">ci_u</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Norte</td>
<td align="left">Norte</td>
<td align="center">0.326</td>
<td align="center">0.048</td>
<td align="center">0.232</td>
<td align="center">0.420</td>
</tr>
<tr class="even">
<td align="left">Sur</td>
<td align="left">Sur</td>
<td align="center">0.295</td>
<td align="center">0.048</td>
<td align="center">0.201</td>
<td align="center">0.389</td>
</tr>
<tr class="odd">
<td align="left">Centro</td>
<td align="left">Centro</td>
<td align="center">0.323</td>
<td align="center">0.072</td>
<td align="center">0.182</td>
<td align="center">0.465</td>
</tr>
<tr class="even">
<td align="left">Occidente</td>
<td align="left">Occidente</td>
<td align="center">0.367</td>
<td align="center">0.044</td>
<td align="center">0.281</td>
<td align="center">0.454</td>
</tr>
<tr class="odd">
<td align="left">Oriente</td>
<td align="left">Oriente</td>
<td align="center">0.387</td>
<td align="center">0.092</td>
<td align="center">0.208</td>
<td align="center">0.567</td>
</tr>
</tbody>
</table>
<p>El interés se centra en realizar los contrastes siguientes para pobreza:</p>
<p><span class="math inline">\(\hat{p}_{Norte} - \hat{p}_{Centro}\)</span>,
<span class="math inline">\(\hat{p}_{Sur}-\hat{p}_{Centro}\)</span><br />
<span class="math inline">\(\hat{p}_{Occidente}-\hat{p}_{Oriente}\)</span></p>
<p>Escrita de forma matricial es:</p>
<p><span class="math display">\[
\left[\begin{array}{ccccc}
1 &amp; 0 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 1 &amp; -1 &amp; 0 &amp; 0\\
0 &amp; 0 &amp; 0 &amp; 1 &amp; -1
\end{array}\right]
\]</span></p>
<p>Y, utilizando la función <code>svycontrast</code> se obtiene:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="tablas-cruzadas.html#cb180-1" tabindex="-1"></a><span class="fu">svycontrast</span>(tab_region_pobreza, <span class="fu">list</span>(</span>
<span id="cb180-2"><a href="tablas-cruzadas.html#cb180-2" tabindex="-1"></a>                <span class="at">Norte_sur =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb180-3"><a href="tablas-cruzadas.html#cb180-3" tabindex="-1"></a>                <span class="at">Sur_centro =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>),</span>
<span id="cb180-4"><a href="tablas-cruzadas.html#cb180-4" tabindex="-1"></a>                <span class="at">Occidente_Oriente =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="sc">-</span><span class="dv">1</span>))) <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code></pre></div>
<pre><code>##                       contrast         SE
## Norte_sur          0.002888908 0.08663389
## Sur_centro        -0.028718759 0.08660027
## Occidente_Oriente -0.019734641 0.10162205</code></pre>
</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0" line-spacing="2">
<div id="ref-heeringa2017applied" class="csl-entry">
Heeringa, S. G., West, B. T., Heeringa, S. G., &amp; Berglund, P. A. (2017). <em>Applied survey data analysis</em>. chapman; hall/CRC.
</div>
<div id="ref-rao1984chisquare" class="csl-entry">
Rao, J. N. K., &amp; Scott, A. J. (1984). On chi-squared tests for multiway contingency tables with cell proportions estimated from survey data. <em>The Annals of Statistics</em>, <em>12</em>(1), 46-60.
</div>
<div id="ref-thomas1987chisquare" class="csl-entry">
Thomas, D. R., &amp; Rao, J. N. K. (1987). Small-sample comparisons of level and power for simple goodness-of-fit statistics under cluster sampling. <em>Journal of the American Statistical Association</em>, <em>82</em>(398), 630-636.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="estimación-de-proporciones.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="viz-categoricas.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/psirusteam/2021ASDA/05-Categóricas.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["Análisis de encuestas con R.pdf", "Análisis de encuestas con R.epub", "Análisis de encuestas con R.mobi"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "section"
  },
  "tconfig": null
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
